platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!
target 'Test_Testure' do
pod 'AFNetworking'
pod 'SDWebImage' , '~> 3.7.3'
pod 'MJExtension'
pod 'MJRefresh'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'Masonry', '~> 0.6.2'
pod 'Texture','~> 2.0'
end



post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ARCHS'] = 'armv7 arm64'
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end


